### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by edision** [featurist/sworm#4] opened 2015-09-05 14:49 UTC
### Unhandled rejection TypeError: Cannot read property 'length' of undefined
```
    at D:\DevResearch\NODEJS\projects\connmssql\node_modules\sworm\index.js:9:22
    at tryCatcher (D:\DevResearch\NODEJS\projects\connmssql\node_modules\sworm\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._resolveFromResolver (D:\DevResearch\NODEJS\projects\connmssql\node_modules\sworm\node_modules\bluebird\js\main\promise.js:476:31)
    at new Promise (D:\DevResearch\NODEJS\projects\connmssql\node_modules\sworm\node_modules\bluebird\js\main\promise.js:69:37)
    at gen1_listComprehension (D:\DevResearch\NODEJS\projects\connmssql\node_modules\sworm\index.js:4:16)
    at D:\DevResearch\NODEJS\projects\connmssql\node_modules\sworm\index.js:478:52
    at tryCatcher (D:\DevResearch\NODEJS\projects\connmssql\node_modules\sworm\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (D:\DevResearch\NODEJS\projects\connmssql\node_modules\sworm\node_modules\bluebird\js\main\promise.js:503:31)
    at Promise._settlePromiseAt (D:\DevResearch\NODEJS\projects\connmssql\node_modules\sworm\node_modules\bluebird\js\main\promise.js:577:18)
    at Async._drainQueue (D:\DevResearch\NODEJS\projects\connmssql\node_modules\sworm\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (D:\DevResearch\NODEJS\projects\connmssql\node_modules\sworm\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\DevResearch\NODEJS\projects\connmssql\node_modules\sworm\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

when I query data by 
```
model.query('select * from tablename').then(function(records){
// when table is not empty
if(records.length > 0) { // records.length will throw err Cannot read property 'length' of undefined
}
});
```

I'm sure that, records is not empty,and I print it,the result is 
```
[{id:1, name:'james'}]
```

**Comment by refractalize** [comment] 2015-09-07 09:33
hi @edision what sort of connection are you using? sql server?

**Comment by refractalize** [comment] 2015-09-07 09:42
Don't seem to be able to reproduce this. Which version of SQL server are you using? Which version of `mssql` are you using? Can you give some more details to reproduce?

**Comment by refractalize** [comment] 2016-03-10 21:58
not able to reproduce this so I'm closing it. Please reopen if you can provide more info.

**Closed by refractalize** 2016-03-10 21:58 UTC
